name: Build Docker Image

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets. DOCKER_PASSWORD }}

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-name: my-app
      tags: |
        utsavgarg007/spring-boot-app:${{ github.sha }}
      push: true
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
